### ISSUE TITLE
built ACISpark on centos7

### ISSUE THREAD

**Issue by zwxhnu** [project-alchemist/ACISpark#8]
I successfully built the alchemist environment on one node, but when I built the ACISpark environment on another node, I had some problems.
After installing java and spark, I clone ACISpark from https://github.com/project-alchemist/ACISpark and modifying the path of ACISpark in the config.sh file, and then successfully executed ./build.sh, but when executing ./start.sh "java.lang.ClassNotFoundException: alchemist.TestSvd" the error has appeared.

![image](https://user-images.githubusercontent.com/17782466/62407345-8c750f00-b5e9-11e9-9259-084d88478921.png)
![image](https://user-images.githubusercontent.com/17782466/62407345-8c750f00-b5e9-11e9-9259-084d88478921.png)

**Comment by zwxhnu** [comment]
I want to know if I am missing some dependencies when I built it, or should I make some changes to the code?

**Comment by QiaowenYoung** [comment]
I also encountered this error on Ubuntu16.04.
But I noticed that the name of .jar under the directory $ACISPARK_PATH/target/scala-2.11 is actually a**lchemist-assembly-0.5.jar**, not **aci-spark-assembly-0.5.jar**, so I modified the start.sh file.
Then it shows like this:
<img width="478" alt="捕获" src="https://user-images.githubusercontent.com/52476919/62448393-4e6b1d00-b79a-11e9-9dc0-a664e132c7d1.PNG">
After that, I created a **log4j.properties** file under the directory $SPARK_PATH/conf, copying from the **log4j.properties.template**, but it shows this:
<img width="347" alt="3" src="https://user-images.githubusercontent.com/52476919/62448432-62168380-b79a-11e9-8a16-ab7885455fd0.PNG">

**Comment by QiaowenYoung** [comment]
I want to know if I need to write log4j.properties on my own, and if so, how?

**Comment by pkhamutou** [comment]
Hi guys,
It should work now. It happened because the class was renamed but `start.sh` script was not updated.

**Comment by kai-rothauge** [comment]
Hi everyone,

Apologies for the late reply to this thread. I've finally updated the readme with some basic usage instructions, sorry that I didn't do this before and the confusion that it caused. The script files config.sh, build.sh and start.sh are deprecated at this point, see the readme for building and running the code, although feel free to put those instructions in a script if you wish. log4j.properties doesn't have to be changed to run ACISpark.

Let me know if you get it to work or not.

Thanks,
Kai




On Monday, August 5, 2019, 06:37:48 a.m. PDT, Pavel Khamutou <notifications@github.com> wrote: 





Hi guys,
I should work now. It happened because the class was renamed but start.sh script was not updated.
